site_name: IPv6 VPN

theme:
  name: material

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mikaelhg

repo_name: mikaelhg/vpn-ipv6
repo_url: https://github.com/mikaelhg/vpn-ipv6
