site_name: IPv6 VPN

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mikaelhg
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MikaelGueck

repo_name: mikaelhg/vpn-ipv6
repo_url: https://github.com/mikaelhg/vpn-ipv6
edit_uri: ""