---
- name: "provision all"
  hosts: all
  become: true
  tasks:

    - name: apt update dist-upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: install wireguard and network stuff
      apt:
        name: [wireguard, resolvconf, nftables, net-tools]
        state: latest

    - name: install shadowsocks
      apt:
        name: [shadowsocks-libev]
        state: latest

    - name: remove ufw
      apt:
        name: [ufw]
        state: absent

    - name: Add user
      user:
        name: mikael
        shell: /bin/bash

    - name: Sudoers
      copy:
        dest: /etc/sudoers.d/mikael
        owner: root
        group: root
        content: |
          mikael ALL=(ALL) NOPASSWD: ALL

    - name: Set authorized key
      authorized_key:
        user: mikael
        state: present
        key: "{{ lookup('file', '/home/mikael/.ssh/id_rsa.pub') }}"

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted

- name: "provision gateways"
  hosts: gateways
  become: true
  tasks:

    - name: install tayga
      apt:
        name: [tayga]
        state: present

    - name: Wireguard configuration
      template:
        src: ./conf/gateway-wg0.conf
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600

    - name: enable wg-quick@wg0
      systemd:
        name: "wg-quick@wg0"
        state: started
        enabled: yes

    - name: enable IPv6 forwarding
      sysctl:
        sysctl_file: /etc/sysctl.d/99-wireguard-route.conf
        name: net.ipv6.conf.all.forwarding
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Download CoreDNS installation package
      get_url:
        dest: /tmp
        url: "https://github.com/coredns/coredns/releases/download/v1.7.0/coredns_1.7.0_linux_amd64.tgz"
        checksum: "sha256:3cb68051ef67a9c747dad20d02ecd4f937f0002a0d053dd557791a1ff4185c4a"

    - name: Install CoreDNS binary from GitHub
      unarchive:
        src: /tmp/coredns_1.7.0_linux_amd64.tgz
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root

#    - name: Download DNSCrypt-proxy
#      get_url:
#        dest: /tmp
#        url: "https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.44/dnscrypt-proxy-linux_x86_64-2.0.44.tar.gz"
#        checksum: "sha256:37ee2c2bbaeb2c3195d903334182c2c4c101560e90e805816b68c2b5aa85845a"

    - name: Set up CoreDNS with systemd
      template:
        src: ./conf/coredns-internal.service
        dest: /etc/systemd/system/coredns-internal.service
        owner: root
        group: root
        mode: "0644"

    - name: CoreDNS configuration, main file
      template:
        src: ./conf/Corefile
        dest: /etc/Corefile
        owner: root
        group: root
        mode: 0600

    - name: CoreDNS configuration, hosts
      template:
        src: ./conf/poc.vpn.hosts
        dest: /etc/poc.vpn.hosts
        owner: root
        group: root
        mode: 0600

- name: "provision home machines"
  hosts: homes
  become: true
  tasks:

    - name: Wireguard configuration
      template:
        src: ./conf/home1-wg0.conf
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600

    - name: enable wg-quick@wg0
      systemd:
        name: "wg-quick@wg0"
        state: started
        enabled: yes

- name: "provision office machines"
  hosts: offices
  become: true
  tasks:
    - name: install wireguard
      apt:
        name: wireguard
        state: present
