name: Documents

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: 1. git checkout
      uses: actions/checkout@v2

    - name: 2. Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: 3. mkdocs build
      # uses: "docker://mikaelhg/mkdocs-material-plantuml:latest"
      uses: 'docker://docker.pkg.github.com/mikaelhg/mkdocs-material-plantuml/mkdocs-material-plantuml:latest'
      # uses: 'mikaelhg/mkdocs-material-plantuml@v1'
      with:
          args: build

    - name: 4. github pages deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
