name: Documents

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: git checkout
      uses: actions/checkout@v2
      
    - name: mkdocs build
      uses: "docker://mikaelhg/mkdocs-material-plantuml:latest"
      with:
          args: build

    - name: github pages deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
